Turn into a full toolchain

diff --git a/create-toolchain b/create-toolchain
--- a/create-toolchain
+++ b/create-toolchain
@@ -1,32 +1,44 @@
 #!/bin/bash
 set -e
-shopt -s extglob
 cd "$(dirname "$0")"
 
 [[ "$(uname -s)" = "Darwin" ]] && is_mac=true
 
 if [[ $# -ne 1 && $# -ne 2 ]]; then 
 	if [[ "${is_mac}" = true ]]; then
-		echo "Usage: $0 <linux version such as ubuntu18.04> [path to xctoolchain]"
+		echo "Usage: $0 <linux version such as ubuntu20.04> [path to xctoolchain]"
 	else
-		echo "Usage: $0 <linux version such as ubuntu18.04> <swift version>"
+		echo "Usage: $0 <swift version> [linux version such as ubuntu20.04]"
 	fi
 	exit 1
 fi
 
 info() { echo "[info] $1"; }
-
-linux_version="$1"
+err() {
+	echo "[error] $1"
+	exit 1
+}
 
 mkdir -p toolchains
 
 if [[ "${is_mac}" = true ]]; then
+	linux_version="$1"
 	mac_toolchain="$(cd "${2:-"$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain"}" && pwd)"
 	swift_version="$("${mac_toolchain}/usr/bin/swift" --version | head -1 | cut -f4 -d" ")"
 	info "Detected Swift version ${swift_version}"
 	cd toolchains
 else
-	swift_version="$2"
+	swift_version="$1"
+	linux_version="$2"
+	if [[ -z "${linux_version}" ]]; then
+		if [[ -f /etc/os-release ]]; then
+			. /etc/os-release
+			linux_version="${ID}${VERSION_ID}"
+			info "Detected Linux version ${linux_version}"
+		else
+			err "Could not auto-detect Linux version; please pass it as the second argument to '$0'."
+		fi
+	fi
 	file_name_mac="swift-${swift_version}-RELEASE-osx"
 	package_mac="${file_name_mac}-package.pkg"
 	info "Downloading macOS toolchain"
@@ -56,24 +68,47 @@ if [[ ! -f "toolchain-${linux_version}-${swift_version}.tar.gz" ]]; then
 fi
 
 info "Unpacking Linux toolchain"
-# remove any pre-existing usr dir first
-rm -rf usr
+# remove any pre-existing linux dir first
+rm -rf linux
 tar -xzf "toolchain-${linux_version}-${swift_version}.tar.gz"
-mv "${file_name_linux}/usr" .
-rm -rf "${file_name_linux}"
+mv "${file_name_linux}" linux
+mv linux/{usr,host}
 
 info "Modifying Linux toolchain"
 
-mv usr/lib/swift{,_linux}
-cp -a "${mac_toolchain}"/usr/lib/{swift,swift-5.0,arc} usr/lib/
-rm usr/lib/swift/clang
-mv usr/lib/swift_linux/clang usr/lib/swift/
+function link_file {
+	# example of $1: linux/host/bin/swiftc
+	usr_path="${1#linux/host/}"
+	iphone_path="linux/iphone/${usr_path}"
+	mkdir -p "$(dirname "${iphone_path}")"
+	# calculate relative path to host file; based on 
+	# https://stackoverflow.com/a/27175714/3769927
+	usr_path_curr="${usr_path}"
+	rel_prefix="../"
+	while [[ "${usr_path_curr}" = */* ]]; do
+		usr_path_curr="${usr_path_curr%/*}"
+		rel_prefix="../${rel_prefix}"
+	done
+	ln -s "${rel_prefix}host/${usr_path}" "${iphone_path}"
+}
+export -f link_file
 
-mv usr/include{,_linux}
-cp -a "${mac_toolchain}"/usr/include usr/
+# symlink all files in these dirs from the host toolchain...
+find linux/host \( -path 'linux/host/bin/*' -o -path 'linux/host/local/*' -o -path 'linux/host/share/*' -o -path 'linux/host/lib/*' \) -and -not -type d -print0 | xargs -0 -I{} bash -c 'link_file "$@"' _ {}
+# ...but replace some components with mac ones...
+rm -rf linux/iphone/lib/swift{,_static}
+cp -a "${mac_toolchain}"/usr/lib/{swift,swift-5.0,arc} linux/iphone/lib/
+cp -a "${mac_toolchain}"/usr/include linux/iphone/include
+# ...but-but replace the mac lib/swift/clang symlink with the linux one
+rm linux/iphone/lib/swift/clang
+link_file linux/host/lib/swift/clang
+
+info "Installing Darwin tools"
+# The hierarchy lines up with ours just right so we dont need to -C
+curl -#L "https://github.com/kabiroberai/darwin-tools-linux/releases/download/v2.0.0/darwin-tools-${linux_version}.tar.gz" | tar -xzf -
 
 info "Packaging toolchain"
 mkdir -p ../packages
-mv usr swift
-tar -czf "../packages/swift-${swift_version}-${linux_version}.tar.gz" swift
-rm -rf swift mac
+# this takes forever but xz is around half the size of gz so imo worth it
+tar -c linux | xz -zvc -T 0 > "../packages/swift-${swift_version}-${linux_version}.tar.xz"
+rm -rf linux mac
